cmake_minimum_required(VERSION 3.24)
project(mfem_parallel_connection LANGUAGES CXX)
find_package(MFEM CONFIG REQUIRED)
add_executable(mfem-connection connection.cpp)
target_link_libraries(mfem-connection PRIVATE mfem)
target_compile_features(mfem-connection PRIVATE cxx_std_17)
set_target_properties(mfem-connection PROPERTIES MSVC_RUNTIME_LIBRARY MultiThreadedDLL)
target_link_options(mfem-connection PRIVATE /MAP /VERBOSE:LIB)
enable_testing()
add_test(NAME mfem-singleton COMMAND mfem-connection)
set_tests_properties(mfem-singleton PROPERTIES TIMEOUT 90 ENVIRONMENT "OMP_NUM_THREADS=1;MKL_NUM_THREADS=1")
